name: aho_corasick_trie
description: Aho-Corasick string search, implemented directly on top of a (slow) trie
version: 0.0.2
repository: https://github.com/ecstatic-morse/aho-corasick-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  glados: ^1.1.3
  lints: ^2.0.0
  test: ^1.16.0
