name: aho_corasick_trie
description: Aho-Corasick string search
version: 0.0.1
repository: https://github.com/ecstaticmorse/aho-corasick-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  glados: ^1.1.3
  lints: ^2.0.0
  test: ^1.16.0
